### ISSUE TITLE
功能改进

### ISSUE THREAD

**Issue by VillagerTom** [joyqi/sfz#11]
建议将实时刷新水印改为点击确定后刷新，以避免输入时卡顿。

**Comment by joyqi** [comment]
这一点倒是没考虑过，实时刷新的时候会卡吗？

**Comment by VillagerTom** [comment]
抱歉账号出了点问题回复晚了。
~~渣机~~测试发现在处理高分辨率图片（3M以上）时会有明显卡顿。
