### ISSUE TITLE
能不能搞个批量功能。一张张来太慢了

### ISSUE THREAD

**Issue by jrotty** [joyqi/sfz#5]
如题，批量可以提高工作效率

**Comment by jzsn2018** [comment]
我扩展了一个js版本，可以支持批量上传和批量水印，批量下载，欢迎star 
https://github.com/jzsn2018/offline-photo-watermark

**Comment by jrotty** [comment]
> 我扩展了一个js版本，可以支持批量上传和批量水印，批量下载，欢迎star https://github.com/jzsn2018/offline-photo-watermark

非常nice，已star
